from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import random
import datetime
import sys

#Gets user/pass data#
def getUsers(file):
    users = []
    with open(file,'r') as f:
        for up in f:
            seperate = up.find(' : ')
            users.append((up[:seperate],up[seperate+3:].strip('\n')))
    return users

#Get list of randomly generated words to search with#
def getWordsRandom(count):
    import string
    resWords = []
    for i in range(0,count):
        resWords.append(''.join(random.choice(string.ascii_lowercase+string.digits) for i in range(random.randint(5,15))))
    return resWords

#Get list of words generated by nytimes to search with
def getWordsFromSite(count):
    from lxml import html
    import requests
    page = requests.get('https://www.nytimes.com')
    summs = html.fromstring(page.text).xpath('//*[@id="top-news"]//*[@class="summary"]')
    resWords = []
    for i in range(0,count):
        words = summs[random.randint(0,len(summs)-1)].text.encode('ascii','ignore').split()
        wordsNum = random.randint(2,min(5,len(words)))
        start = random.randint(0,len(words)-wordsNum)
        resWords.append(' '.join(words[start:start+wordsNum]))
    return resWords

#Open chrome, go to site and login
def getBrowser(unText,pwText,mobile=False):
    site = 'https://login.live.com'
    if mobile:
        mobile_emulation = { "deviceName": "Google Nexus 5" }
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_experimental_option("mobileEmulation", mobile_emulation)
        driver = webdriver.Chrome(desired_capabilities=chrome_options.to_capabilities())
    else:
        driver = webdriver.Chrome()
    driver.set_window_size(300,300)
    driver.get(site)
    unElem = driver.find_element_by_name('loginfmt')
    unElem.send_keys(unText)
    pwElem = driver.find_element_by_name('passwd')
    pwElem.send_keys(pwText)
    si = driver.find_element_by_name('SI')
    si.send_keys(Keys.RETURN)
    if driver.current_url[:len(site)] == site:
        return None
    return driver

#Sleeps for random amount of time
def sleeper(sleep=(3,3)):
    time.sleep(sleep[0]+random.random()*sleep[1])

#Gets points on bing search
def getSearchPoints(driver,words,sleep=(3,3)):
    count = 1
    driver.get('http://www.bing.com')
    time.sleep(1)
    for word in words:
        print '    ' + str(count) + ': Searching: "' + word + '"'
        search = driver.find_element_by_xpath('//*[@id="sb_form_q"]')
        search.send_keys(Keys.CONTROL+'a')
        search.send_keys(Keys.BACKSPACE)
        search.send_keys(word)
        search.send_keys(Keys.ENTER)
        sleeper(sleep)
        count += 1
    return count-1


#Get points on bing by clicking the extra links
def getClickPoints(driver,sleep=(3,3)):
    site = 'https://www.bing.com/rewards/dashboard'
    while True:
        driver.get(site)
        time.sleep(2)
        if driver.find_element_by_xpath('/html/body/div[2]/div[1]').text != 'You are not signed in to Bing Rewards.':
            break
    explores = driver.find_elements_by_xpath('//*[@id="dashboard_wrapper"]/*[@class="offers"]/div[1]//a')
    for explore in explores:
        if 'trivia' not in explore.find_element_by_class_name('title').text.lower() and '0' in explore.find_element_by_class_name('progress').text:
            explore.send_keys(Keys.CONTROL+Keys.ENTER)
            sleeper(sleep)
            if driver.current_url == site:
                driver.find_element_by_tag_name('body').send_keys(Keys.COMMAND + 'r')
                continue
            driver.find_element_by_tag_name('body').send_keys(Keys.COMMAND + keys.TAB)
            driver.find_element_by_tag_name('body').send_keys(Keys.COMMAND + 'w')

if __name__== "__main__":
    run = True
    if len(sys.argv) < 2:
        #check is already ran today
        with open('LastTime.txt','r') as f:
            laststr = f.readline().strip('\n')
            if laststr != '':
                now = datetime.datetime.now()
                last = datetime.datetime.strptime(laststr,'%Y-%m-%d')
                now = datetime.datetime(now.year,now.month,now.day)
                run = now > last
    #run seaches
    if run:
        browserSearches = 31
        mobileSearches = 21

        #read arguments if provided
        if len(sys.argv) > 1:
            div = sys.argv[1].find(',')
            browserSearches = int(sys.argv[1][:div])
            mobileSearches = int(sys.argv[1][div+1:])
        users = getUsers('logins.txt')

        for unText,pwText in users:
            #regular searches
            print "  Regular Searches:"
            driver = getBrowser(unText,pwText)
            if driver is None:
                print 'Failed to login with "' + unText + '"'
                continue
            print 'Username: ' + unText
            words = getWordsFromSite(browserSearches+mobileSearches)
            bcount = getSearchPoints(driver,words[:browserSearches])

            #click for extra points
            getClickPoints(driver)
            driver.close()

            #Mobile searches
            print "  Mobile Searches:"
            driver = getBrowser(unText,pwText,True)
            mcount = getSearchPoints(driver,words[browserSearches:])
            driver.close()

            #Save last time run
            with open('LastTime.txt','w') as f:
                now = datetime.datetime.now()
                f.write(now.strftime('%Y-%m-%d'))

            #Print failed attempts
            if browserSearches - bcount != 0:
                print '  Failed to search ' + str(bcount) + ' regular searches'
            if mobileSearches - mcount != 0:
                print '  Failed to search ' + str(mcount) + ' mobile searches'
        print 'Done!'
    else:
        print 'Already dont for today.'
